package ec;

/**
Fitness: 687
Generated by ECJ2Java on Thu Apr 30 03:57:18 EDT 2015
**/

public class MathSolution2 {

	public double calculate(double x, double AverageOver30s, double AverageOver60s, double AverageOver90s, double AverageOver120s, double RateOfChangeOver30s, double RateOfChangeOver60s, double RateOfChangeOver90s, double RateOfChangeOver120s, double RelativeStrengthIndexOver30s, double RelativeStrengthIndexOver60s, double RelativeStrengthIndexOver90s, double RelativeStrengthIndexOver120s, double MacdValue, double MaxValueOver30s, double MaxValueOver60s, double MaxValueOver90s,  double MaxValueOver120s,  double MinValueOver30s,  double MinValueOver60s,  double MinValueOver90s,  double MinValueOver120s, double VarBwBSandBF60s, double VarBwBSandBF120s, double VarBwBSandBF240s, double VarBwBSandBT60s, double VarBwBSandBT120s, double VarBwBSandBT240s, double VarBwBSandOK60s, double VarBwBSandOK120s, double VarBwBSandOK240s, double VolatilityOver30s, double VolatilityOver60s, double VolatilityOver120s, double KeijzerERC) {
		double func_3 = AverageOver30s + VarBwBSandBT60s;
		double func_4 = Math.cos(Math.toRadians(func_3));
		double func_7 = AverageOver30s + VarBwBSandBT60s;
		double func_9 = Math.log(Math.abs(MinValueOver120s));
		double func_10 = func_9 == 0 ? 0 : func_7 / func_9;
		double func_12 = func_10 - MaxValueOver60s;
		double func_15 = MaxValueOver90s * VolatilityOver120s;
		double func_16 = func_12 + func_15;
		double func_18 = Math.log(Math.abs(RelativeStrengthIndexOver60s));
		double func_21 = VarBwBSandBF120s == 0 ? 0 : VarBwBSandBT60s / VarBwBSandBF120s;
		double func_22 = func_21 == 0 ? 0 : func_18 / func_21;
		double func_23 = func_16 * func_22;
		double func_25 = Math.log(Math.abs(AverageOver120s));
		double func_26 = Math.sin(Math.toRadians(func_25));
		double func_29 = MinValueOver30s + MaxValueOver90s;
		double func_30 = Math.pow(func_29,2);
		double func_31 = func_26 - func_30;
		double func_32 = func_23 * func_31;
		return func_4 + func_32;
	}

}