package ;

/**
Fitness: 22945
Generated by ECJ2Java on Wed Apr 29 01:04:57 EDT 2015
**/

public class MathSolution {

	public double calculate(double x, double AverageOver30s, double AverageOver60s, double AverageOver90s, double AverageOver120s, double RateOfChangeOver30s, double RateOfChangeOver60s, double RateOfChangeOver90s, double RateOfChangeOver120s, double RelativeStrengthIndexOver30s, double RelativeStrengthIndexOver60s, double RelativeStrengthIndexOver90s, double RelativeStrengthIndexOver120s, double MacdValue, double MaxValueOver30s, double MaxValueOver60s, double MaxValueOver90s,  double MaxValueOver120s,  double MinValueOver30s,  double MinValueOver60s,  double MinValueOver90s,  double MinValueOver120s, double VarBwBSandBF60s, double VarBwBSandBF120s, double VarBwBSandBF240s, double VarBwBSandBT60s, double VarBwBSandBT120s, double VarBwBSandBT240s, double VarBwBSandOK60s, double VarBwBSandOK120s, double VarBwBSandOK240s, double VolatilityOver30s, double VolatilityOver60s, double VolatilityOver120s, double KeijzerERC) {
		double func_3 = AverageOver60s * AverageOver90s;
		double func_6 = VarBwBSandBF240s + MaxValueOver60s;
		double func_7 = func_3 - func_6;
		return Math.sin(Math.toRadians(func_7));
	}

}